on:
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab
name: Build Flatpak
jobs:
  flatpak:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.8
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        id: cache
        uses: actions/cache@v4
        with:
          path: .flatpak-builder
          key: flatpak-build-${{ github.sha }}
          restore-keys: flatpak-build
          save-always: true

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: sideband.flatpak
          manifest-path: io.unsigned.sideband.yml
          cache: false
