on:
  workflow_dispatch: # can be manually dispatched under GitHub's "Actions" tab

name: Build Flatpak
jobs:
  flatpak:
    name: Flatpak Builder
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:freedesktop-24.08
      options: --privileged

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Restore Cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: .flatpak-builder
          key: flatpak-build

      - name: Build
        uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: sideband.flatpak
          manifest-path: io.unsigned.sideband.yml
          cache: false

      - name: Save Cache
        id: cache-save
        uses: actions/cache/save@v4
        if: always()
        with:
          path: .flatpak-builder
          key: flatpak-build-${{ github.sha }}
